### ISSUE TITLE
Upgrade Neo4j Driver Dependencies to Latest Version

### ISSUE THREAD

**Issue by as185386** [DotNet4Neo4j/Neo4j.Driver.Extensions#1]
Users of the latest version of the Neo4j driver (4.3.1 at this time) are unable to utilize this product.  Therefore, I recommend upgrading the Neo4j and EnsureThat dependencies to the latest version.

**Comment by cskardon** [comment]
You can use the 4.3.1 version with these extensions.

**Comment by as185386** [comment]
Hey Charlotte!

Thanks for getting back with me!  I realized that I had not referenced the signed version of the Neo4j driver (Neo4j.Driver.Signed versus Neo4j.Driver).  Very cool extension btw!!!

Cya!

***@***.***D773E4.B949FAD0]Andy Stutz
SW Engineer III
NCR Corporation
***@***.******@***.***>  |  ncr.com<http://www.ncr.com/>
***@***.***D773E5.4ABA0910]<https://www.facebook.com/ncrcorp>­  ***@***.***D773E5.4ABA0910] <https://twitter.com/NCRCorporation>    ***@***.***D773E5.4ABA0910] <https://www.linkedin.com/company/ncr-corporation>   ***@***.***D773E4.B949FAD0] <https://www.instagram.com/ncrcorporation/?hl=en>

**Comment by as185386** [comment]
Make sure to reference the signed version of the Neo4j driver (Neo4j.Driver.Signed versus Neo4j.Driver) in Nuget.
