### ISSUE TITLE
Plans to upgrade to latest Driver bindings?

### ISSUE THREAD

**Issue by CharlieDigital** [DotNet4Neo4j/Neo4j.Driver.Extensions#2]
**Is your feature request related to a problem? Please describe.**
Current build is not tracking the latest `Neo4j.Driver` package.

**Describe the solution you'd like**
Updated bindings.

**Describe alternatives you've considered**
Forked and built my own; switched to non-signed `Driver` package.

**Additional context**
Not sure if other folks are interested, but I think it would be great to update the bindings.

**Comment by cskardon** [comment]
Done as part of https://github.com/DotNet4Neo4j/Neo4j.Driver.Extensions/commit/a71432493f6a9d67bc6169897d4749b9325010bb
